### ISSUE TITLE
"division by zero"-error for bam-files without chrM-reads 

### ISSUE THREAD

**Issue by asp8200** [abyzovlab/CNVpytor#117]
Given a bam-file with no mitochondial reads, the following command caused `cnvpytor` to crash:
```
cnvpytor -root foo.pytor -rd foo.bam -T Homo_sapiens_assembly38_chr20_chrM.fasta
```

The error-message:
```
...
2022-06-03 19:15:54,364 - cnvpytor.root - INFO - Chromosome 'chrM' stat
2022-06-03 19:15:54,367 - cnvpytor.root - INFO - Autosomes stat - RD parity distribution gaussian fit:  0.00 +- 0.00
2022-06-03 19:15:54,370 - cnvpytor.root - INFO - Mitochondria stat - RD parity distribution gaussian fit:  0.00 +- 0.00
Traceback (most recent call last):
  File "/home/andersp/anaconda3/envs/nextflow/bin/cnvpytor", line 10, in <module>
    sys.exit(main())
  File "/home/andersp/anaconda3/envs/nextflow/lib/python3.7/site-packages/cnvpytor/__main__.py", line 270, in main
    app.rd(args.rd, chroms=args.chrom, reference_filename=args.reference_filename)
  File "/home/andersp/anaconda3/envs/nextflow/lib/python3.7/site-packages/cnvpytor/root.py", line 319, in rd
    self.rd_stat()
  File "/home/andersp/anaconda3/envs/nextflow/lib/python3.7/site-packages/cnvpytor/root.py", line 237, in rd_stat
    2. * m_mt / m_auto, 2. * s_mt / m_auto + s_auto * m_mt / (m_auto * m_auto)))
ZeroDivisionError: float division by zero
```

I found it inconvenient for my usage of cnvpytor. I would find it more convenient if cnvpytor juse left the mitochondia stats as undefined in such cases.

**Comment by arpanda** [comment]
I'm not sure I understand the query. If you would like to filter out any chromosome, please use the `-chrom` parameter. If `-chrom` parameter is provided, CNVpytor will use those chromosomes only and skip the others.  

See https://github.com/abyzovlab/CNVpytor/blob/master/GettingStarted.md#import-read-depth-signal . 

Thanks 
Arijit
