### ISSUE TITLE
cnvpytor 1.2.1 -genotype step issue: "NameError: name 'raw_input' is not defined"

### ISSUE THREAD

**Issue by jordimaggi** [abyzovlab/CNVpytor#123]
Hi,

I have been running cnvpytor 1.0 on another machine wihtout any errors. I setup a new machine with version cnvpytor version 1.2.1 and run the same script.

This is the script I use:

```
#!/usr/bin/bash

sample="73446"

exec > "/Console_outputs/CNVpytor_terminal.$sample.log" 2>&1
start=$(date)
echo $start
echo "Starting CNVpytor command for sample $sample"
SECONDS=0
echo ' '

cnvpytor -root /media/analyst/Data/WGS/$sample/SV_calling/CNVpytor/$sample"".pytor -rd /media/analyst/Data/WGS/$sample/$sample""_WGS_hg19_recalibrated.sorted.bam
echo "Finished RD command"
cnvpytor -root /media/analyst/Data/WGS/$sample/SV_calling/CNVpytor/$sample"".pytor -his 1000 10000 100000
echo "Finished HIS command"
cnvpytor -root /media/analyst/Data/WGS/$sample/SV_calling/CNVpytor/$sample"".pytor -partition 1000 10000 100000
echo "Finished Partition command"
cnvpytor -root /media/analyst/Data/WGS/$sample/SV_calling/CNVpytor/$sample"".pytor -call 1000 > /media/analyst/Data/WGS/$sample/SV_calling/CNVpytor/$sample""_SV_cnvpytor_command.tsv
echo "Finished Call command"
cnvpytor -root /media/analyst/Data/WGS/$sample/SV_calling/CNVpytor/$sample"".pytor -snp /media/analyst/Data/WGS/$sample/$sample""_WGS_hg19_haplotypecaller_filtered.vcf.gz -sample $sample
echo "Finished SNP command"
cnvpytor -root /media/analyst/Data/WGS/$sample/SV_calling/CNVpytor/$sample"".pytor -mask_snps
echo "Finished Mask SNPs command"
cnvpytor -root /media/analyst/Data/WGS/$sample/SV_calling/CNVpytor/$sample"".pytor -baf 10000 100000
echo "Finished BAF command"
cnvpytor -root /media/analyst/Data/WGS/$sample/SV_calling/CNVpytor/$sample"".pytor -genotype 10000 100000
echo "Finished genotype command"
cnvpytor -root /media/analyst/Data/WGS/$sample/SV_calling/CNVpytor/$sample"".pytor -plot rd  10000 100000 likelihood  10000 100000 baf 10000 100000 snp -o /media/analyst/Data/WGS/$sample/SV_calling/CNVpytor/$sample""_cnvpytor_wide.png
echo "Finished Plot RD command"
cnvpytor -root /media/analyst/Data/WGS/$sample/SV_calling/CNVpytor/$sample"".pytor -plot manhattan 10000 100000 -chrom chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 \
		chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22 chrX chrY chrM -o /media/analyst/Data/WGS/$sample/SV_calling/CNVpytor/$sample""_cnvpytor_manhattan.png
echo "Finished Plot manhattan command"
cnvpytor -root /media/analyst/Data/WGS/$sample/SV_calling/CNVpytor/$sample"".pytor -plot circular 10000 100000 -chrom chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 \
		chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22 chrX chrY chrM -o /media/analyst/Data/WGS/$sample/SV_calling/CNVpytor/$sample""_cnvpytor_circular.png
echo "Finished Plot circular command"
echo ' '
end=$(date)
echo $end
duration=$SECONDS
echo "CNVpytor command for sample $sample completed."
echo "The analysis completed in $(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed."
```

Version `1.0` completes without issues within 60 minutes.
Version `1.2.1` gets stuck on step `-genotype` for days wihtout printing any error message. When I stop execution it print the following error message:

```
Traceback (most recent call last):
  File "/home/analyst/anaconda3/envs/SV_packages_py3_env/lib/python3.7/site-packages/cnvpytor/viewer.py", line 4046, in genotype_prompt
    line = raw_input("")
NameError: name 'raw_input' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/analyst/anaconda3/envs/SV_packages_py3_env/bin/cnvpytor", line 10, in <module>
    sys.exit(main())
  File "/home/analyst/anaconda3/envs/SV_packages_py3_env/lib/python3.7/site-packages/cnvpytor/__main__.py", line 232, in main
    view.genotype_prompt(list(map(binsize_type, args.genotype)), all=args.all)
  File "/home/analyst/anaconda3/envs/SV_packages_py3_env/lib/python3.7/site-packages/cnvpytor/viewer.py", line 4048, in genotype_prompt
    line = input("")
```

I also attached the entire console output (CNVpytor_terminal.73446.log)
[CNVpytor_terminal.73446.log](https://github.com/abyzovlab/CNVpytor/files/9093176/CNVpytor_terminal.73446.log)
.

**Comment by arpanda** [comment]
The `-genotype` command looks for a input. Here you can find the details https://github.com/abyzovlab/CNVpytor/wiki/4.-Genotyping-genomic-regions . 

I am not sure what is your purpose for using `-genotype` command. To me, it's not needed for your script for CNVpytor<sub>v1.2.1 </sub> 

Thanks
Arijit
