### ISSUE TITLE
ValueError in 2D/BAF calling

### ISSUE THREAD

**Issue by maryawood** [abyzovlab/CNVpytor#124]
Hello,

I've run into this error a few times when doing BAF or combined read depth/BAF calling:

```
Traceback (most recent call last):
  File "/home/ubuntu/.snakemake/conda/84ce1bf17a97deb187fccc51ad01bf71/bin/cnvpytor", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/.snakemake/conda/84ce1bf17a97deb187fccc51ad01bf71/lib/python3.9/site-packages/cnvpytor/__main__.py", line 309, in main
    app.call_2d(list(map(binsize_type, args.call[1:])), chroms=args.chrom, print_calls=True,
  File "/home/ubuntu/.snakemake/conda/84ce1bf17a97deb187fccc51ad01bf71/lib/python3.9/site-packages/cnvpytor/root.py", line 2041, in call_2d
    dmin = np.min(data)
  File "<__array_function__ internals>", line 180, in amin
  File "/home/ubuntu/.snakemake/conda/84ce1bf17a97deb187fccc51ad01bf71/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 2916, in amin
    return _wrapreduction(a, np.minimum, 'min', axis, None, out,
  File "/home/ubuntu/.snakemake/conda/84ce1bf17a97deb187fccc51ad01bf71/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity
```

It's happened in cases of samples with fairly low coverage, so I'm guessing that there is insufficient data to predict any variants with BAF? Even with increased verbosity there's not much information about the error, so I was curious whether this is known issue/if there's some minimum variant count requirement or something for VCFs? Thanks!

**Comment by suvakov** [comment]
Hi, we are trying to to reproduce this error. Can you share your "pytor" file with us? Thanks
