### ISSUE TITLE
BUG: invalid shape

### ISSUE THREAD

**Issue by gevro** [abyzovlab/CNVpytor#13]
Hi,
I upgraded to the latest CNVpytor and I'm getting this error I have never seen before.

[evrong01@bigpurple-ln1 CNVpytor]$ cnvpytor -root UDP-1103_genome.cnvpytor.root -view 10000
cnvpytor> set panels rd likelihood baf
    * panels: ['rd', 'likelihood', 'baf']
cnvpytor> set legend
    * legend: True
cnvpytor> set rd_use_mask
    * rd_use_mask: True
cnvpytor> chr1
Traceback (most recent call last):
  File "/gpfs/home/evrong01/.local/lib/python3.6/site-packages/cnvpytor/viewer.py", line 458, in prompt
    self.parse(f + [str(self.bin_size)])
  File "/gpfs/home/evrong01/.local/lib/python3.6/site-packages/cnvpytor/viewer.py", line 355, in parse
    self.multiple_regions(regions)
  File "/gpfs/home/evrong01/.local/lib/python3.6/site-packages/cnvpytor/viewer.py", line 1190, in multiple_regions
    self.regions(ix[i], r)
  File "/gpfs/home/evrong01/.local/lib/python3.6/site-packages/cnvpytor/viewer.py", line 1510, in regions
    ax.imshow(img, aspect='auto')
  File "/gpfs/home/evrong01/.local/lib/python3.6/site-packages/matplotlib/__init__.py", line 1565, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/gpfs/home/evrong01/.local/lib/python3.6/site-packages/matplotlib/cbook/deprecation.py", line 358, in wrapper
    return func(*args, **kwargs)
  File "/gpfs/home/evrong01/.local/lib/python3.6/site-packages/matplotlib/cbook/deprecation.py", line 358, in wrapper
    return func(*args, **kwargs)
  File "/gpfs/home/evrong01/.local/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 5615, in imshow
    im.set_data(X)
  File "/gpfs/home/evrong01/.local/lib/python3.6/site-packages/matplotlib/image.py", line 699, in set_data
    .format(self._A.shape))
TypeError: Invalid shape (0,) for image data

cnvpytor> ls

Filename 'UDP-1103_genome.cnvpytor.root'
----------------------------------------
File created: 2020-07-19 17:12 using CNVpytor ver 1.0

Chromosomes with RD signal: chr1, chr2, chr3, chr4, chr5, chr6, chr7, chr8, chr9, chr10, chr11, chr12, chr13, chr14, chr15, chr16, chr17, chr18, chr19, chr20, chr21, chr22, chrX, chrY

Chromosomes with SNP signal: 

Using reference genome: hg38 [ GC: yes, mask: yes ]

Chromosomes with RD histograms [bin sizes]: chr10, chr11, chr12, chr13, chr14, chr15, chr16, chr17, chr18, chr19, chr1, chr20, chr21, chr22, chr2, chr3, chr4, chr5, chr6, chr7, chr8, chr9, chrX, chrY [1000, 10000, 100000]

Chromosomes with SNP histograms [bin sizes]:  []

Chromosome lengths: {'chr1': '248956422', 'chr2': '242193529', 'chr3': '198295559', 'chr4': '190214555', 'chr5': '181538259', 'chr6': '170805979', 'chr7': '159345973', 'chr8': '145138636', 'chr9': '138394717', 'chr10': '133797422', 'chr11': '135086622', 'chr12': '133275309', 'chr13': '114364328', 'chr14': '107043718', 'chr15': '101991189', 'chr16': '90338345', 'chr17': '83257441', 'chr18': '80373285', 'chr19': '58617616', 'chr20': '64444167', 'chr21': '46709983', 'chr22': '50818468', 'chrX': '156040895', 'chrY': '57227415'}

**Comment by gevro** [comment]
I think it has something to do with not reading in the VCF files. Because "Chromosomes with SNP signal" and "Chromosomes with SNP histograms" is blank. However, there was no error in reading the VCF files.

cnvpytor -root cnvpytor.root -snp VCFfile.vcf.gz -sample UDP-1103_genome -chrom chr1 chr2 chr3 ...

2020-07-19 18:03:09,070 - cnvpytor.root - INFO - Reading variant data for chromosome chr1
2020-07-19 18:03:11,811 - cnvpytor.root - INFO - Reading variant data for chromosome chr2
2020-07-19 18:03:14,495 - cnvpytor.root - INFO - Reading variant data for chromosome chr3
2020-07-19 18:03:16,731 - cnvpytor.root - INFO - Reading variant data for chromosome chr4
2020-07-19 18:03:19,081 - cnvpytor.root - INFO - Reading variant data for chromosome chr5
2020-07-19 18:03:21,103 - cnvpytor.root - INFO - Reading variant data for chromosome chr6
2020-07-19 18:03:23,238 - cnvpytor.root - INFO - Reading variant data for chromosome chr7
2020-07-19 18:03:25,161 - cnvpytor.root - INFO - Reading variant data for chromosome chr8
2020-07-19 18:03:26,825 - cnvpytor.root - INFO - Reading variant data for chromosome chr9
2020-07-19 18:03:28,376 - cnvpytor.root - INFO - Reading variant data for chromosome chr10
2020-07-19 18:03:30,099 - cnvpytor.root - INFO - Reading variant data for chromosome chr11
2020-07-19 18:03:31,712 - cnvpytor.root - INFO - Reading variant data for chromosome chr12
2020-07-19 18:03:33,285 - cnvpytor.root - INFO - Reading variant data for chromosome chr13
2020-07-19 18:03:34,580 - cnvpytor.root - INFO - Reading variant data for chromosome chr14
2020-07-19 18:03:35,672 - cnvpytor.root - INFO - Reading variant data for chromosome chr15
2020-07-19 18:03:36,657 - cnvpytor.root - INFO - Reading variant data for chromosome chr16
2020-07-19 18:03:37,728 - cnvpytor.root - INFO - Reading variant data for chromosome chr17
2020-07-19 18:03:38,720 - cnvpytor.root - INFO - Reading variant data for chromosome chr18
2020-07-19 18:03:39,654 - cnvpytor.root - INFO - Reading variant data for chromosome chr19
2020-07-19 18:03:40,420 - cnvpytor.root - INFO - Reading variant data for chromosome chr20
2020-07-19 18:03:41,337 - cnvpytor.root - INFO - Reading variant data for chromosome chr21
2020-07-19 18:03:41,945 - cnvpytor.root - INFO - Reading variant data for chromosome chr22
2020-07-19 18:03:42,573 - cnvpytor.root - INFO - Reading variant data for chromosome chrX
2020-07-19 18:03:43,703 - cnvpytor.root - INFO - Reading variant data for chromosome chrY

**Comment by suvakov** [comment]
Yes, first error is due to lack of SNP data. There is no error in -snp step, however there are no SNP-s (it logs "Saving SNP data for chromosome ...." where there are data for the chromosome). I am guessing that there are no SNPs with PASS filter or there is no AD tag. Can you copy here or email me if confidential few lines of vcf file (after header) to check?

**Comment by gevro** [comment]
Yes you are correct. It was missing PASS in the FILTER column. Now it works. Thanks.
