### ISSUE TITLE
Can't genotype via command line

### ISSUE THREAD

**Issue by luizagomesdeoliveira** [abyzovlab/CNVpytor#138]
I have a .pytor file created via cnyptor but I can't genotype my data via command line. No message is printed in terminal asking me to enter a region, so I tried writing the region in the terminal and entering it. 

With this command line: `cnvpytor -root jap.pytor -genotype 10000 100000` and these regions: `1:103655519-103664554` and `chr1:103655519-103664554`

I get the error: 
```
_File "/home/luiza/anaconda3/bin/cnvpytor", line 33, in <module>
    sys.exit(load_entry_point('CNVpytor==1.2.1', 'console_scripts', 'cnvpytor')())
  File "/home/luiza/anaconda3/lib/python3.9/site-packages/cnvpytor/__main__.py", line 234, in main
    view.genotype_prompt(list(map(binsize_type, args.genotype)), all=args.all)
  File "/home/luiza/anaconda3/lib/python3.9/site-packages/cnvpytor/viewer.py", line 4191, in genotype_prompt
    self.genotype(bin_sizes, line, interactive=True)
  File "/home/luiza/anaconda3/lib/python3.9/site-packages/cnvpytor/viewer.py", line 3904, in genotype
    print("\t%f" % (2. * rc / (stat[4] * (pos2 - pos1 + 1) / bs)), end="")
IndexError: list index out of range_
```
Whit this command line: `cnvpytor -root jap.pytor -genotype ` and these regions: `1:103655519-103664554` and `chr1:103655519-103664554`

I get the error:
```
_File "/home/luiza/anaconda3/lib/python3.9/site-packages/cnvpytor/viewer.py", line 4180, in genotype_prompt
    line = raw_input("")
NameError: name 'raw_input' is not defined_

_During handling of the above exception, another exception occurred:_

_Traceback (most recent call last):
  File "/home/luiza/anaconda3/bin/cnvpytor", line 33, in <module>
    sys.exit(load_entry_point('CNVpytor==1.2.1', 'console_scripts', 'cnvpytor')())
  File "/home/luiza/anaconda3/lib/python3.9/site-packages/cnvpytor/__main__.py", line 234, in main
    view.genotype_prompt(list(map(binsize_type, args.genotype)), all=args.all)
  File "/home/luiza/anaconda3/lib/python3.9/site-packages/cnvpytor/viewer.py", line 4182, in genotype_prompt
    line = input("")_
```
For every run I used one type of command line and one type of region.

These errors only apear to me after keyboard interuption since once looking at the current process in my machine, CNVpytor seems to have stopped running.

Thank you in advance,

Luiza Gomes

**Comment by luizagomesdeoliveira** [comment]
I tried running the Predicting CNV regions command lines and was able to genotype!
