### ISSUE TITLE
RD histogram stage - IndexError: list index out of range

### ISSUE THREAD

**Issue by bjhunt-git** [abyzovlab/CNVpytor#140]
Hi, many thanks for creating CNVpytor - I have an issue with running it with my own reference genome, any assistance would be much appreciated.

Installation and commands as follows:

```
git clone https://github.com/abyzovlab/CNVpytor.git
cd CNVpytor/
pip install .

cnvpytor -conf $CONF -root $OUTPUT/A10237_1.pytor -rd $BAM/A10237_1/A10237_1.sorted.dup.bam -T $GENOME/NS.six.chr.fasta -rg mpns
cnvpytor -conf $CONF -root $OUTPUT/A10237_1.pytor -his 100000
cnvpytor -conf $CONF -root $OUTPUT/A10237_1.pytor -partition 100000
cnvpytor -conf $CONF -root $OUTPUT/A10237_1.pytor -call 100000 > calls.100000.tsv
```

The output .tsv file is empty and the log file shows the following:

```
2022-09-28 16:46:41,447 - cnvpytor.genome - INFO - Reading configuration file '/nobackup/beegfs/workspace/bh471/scripts/ma_imi/cnvpytor/mper_ns_ref_genome_conf.py'.
2022-09-28 16:46:41,448 - cnvpytor.genome - INFO - Importing reference genome data: 'mpns'.
2022-09-28 16:46:41,851 - cnvpytor.bam - INFO - File: /nobackup/beegfs/workspace/bh471/data/projects/ma_imi/cnv/cnvpytor/aligned/A10237_1/A10237_1.sorted.dup.bam successfully open
2022-09-28 16:46:41,886 - cnvpytor.pool - INFO - Parallel processing using 8 cores
2022-09-28 16:46:41,947 - cnvpytor.root - INFO - Reading data for chromosome HiC_scaffold_1 with length 101541550
2022-09-28 16:46:41,948 - cnvpytor.root - INFO - Reading data for chromosome HiC_scaffold_2 with length 85525568
2022-09-28 16:46:41,948 - cnvpytor.root - INFO - Reading data for chromosome HiC_scaffold_3 with length 69707339
2022-09-28 16:46:41,948 - cnvpytor.root - INFO - Reading data for chromosome HiC_scaffold_4 with length 62390805
2022-09-28 16:46:41,948 - cnvpytor.root - INFO - Reading data for chromosome HiC_scaffold_5 with length 29725293
2022-09-28 16:46:41,948 - cnvpytor.root - INFO - Reading data for chromosome HiC_scaffold_6 with length 29628513
2022-09-28 16:49:49,329 - cnvpytor.io - INFO - Saving chromosome RD data for chromosome 'HiC_scaffold_1'.
2022-09-28 16:49:49,846 - cnvpytor.io - INFO - Saving chromosome RD data for chromosome 'HiC_scaffold_2'.
2022-09-28 16:49:50,199 - cnvpytor.io - INFO - Saving chromosome RD data for chromosome 'HiC_scaffold_3'.
2022-09-28 16:49:50,489 - cnvpytor.io - INFO - Saving chromosome RD data for chromosome 'HiC_scaffold_4'.
2022-09-28 16:49:50,736 - cnvpytor.io - INFO - Saving chromosome RD data for chromosome 'HiC_scaffold_5'.
2022-09-28 16:49:50,866 - cnvpytor.io - INFO - Saving chromosome RD data for chromosome 'HiC_scaffold_6'.
2022-09-28 16:49:52,489 - cnvpytor.root - INFO - Reference genome 'mpns' found in database.
2022-09-28 16:49:52,491 - cnvpytor.root - INFO - GC content for reference genome 'mpns' found in database.
2022-09-28 16:49:54,331 - cnvpytor.genome - INFO - Reading configuration file '/nobackup/beegfs/workspace/bh471/scripts/ma_imi/cnvpytor/mper_ns_ref_genome_conf.py'.
2022-09-28 16:49:54,334 - cnvpytor.genome - INFO - Importing reference genome data: 'mpns'.
2022-09-28 16:49:54,381 - cnvpytor.root - INFO - Reference genome 'mpns' found in database.
2022-09-28 16:49:54,384 - cnvpytor.root - INFO - GC content for reference genome 'mpns' found in database.
2022-09-28 16:49:54,393 - cnvpytor.root - INFO - Calculating histograms using bin size 100000 for chromosome 'HiC_scaffold_1'.
2022-09-28 16:49:54,507 - cnvpytor.root - INFO - Chromosome 'HiC_scaffold_1' bin size 100000 stat - RD parity distribution gaussian fit:  38035.32 +- 4111.72
2022-09-28 16:49:54,507 - cnvpytor.root - INFO - Chromosome 'HiC_scaffold_1' bin size 100000 stat - RD unique distribution gaussian fit:  34995.90 +- 5100.59
2022-09-28 16:49:54,508 - cnvpytor.root - INFO - Calculating histograms using bin size 100000 for chromosome 'HiC_scaffold_2'.
2022-09-28 16:49:54,604 - cnvpytor.root - INFO - Chromosome 'HiC_scaffold_2' bin size 100000 stat - RD parity distribution gaussian fit:  38821.45 +- 3440.61
2022-09-28 16:49:54,605 - cnvpytor.root - INFO - Chromosome 'HiC_scaffold_2' bin size 100000 stat - RD unique distribution gaussian fit:  37026.67 +- 4067.37
2022-09-28 16:49:54,606 - cnvpytor.root - INFO - Calculating histograms using bin size 100000 for chromosome 'HiC_scaffold_3'.
2022-09-28 16:49:54,677 - cnvpytor.root - INFO - Chromosome 'HiC_scaffold_3' bin size 100000 stat - RD parity distribution gaussian fit:  39724.14 +- 3767.66
2022-09-28 16:49:54,677 - cnvpytor.root - INFO - Chromosome 'HiC_scaffold_3' bin size 100000 stat - RD unique distribution gaussian fit:  37967.35 +- 4155.31
2022-09-28 16:49:54,678 - cnvpytor.root - INFO - Calculating histograms using bin size 100000 for chromosome 'HiC_scaffold_4'.
2022-09-28 16:49:54,762 - cnvpytor.root - INFO - Chromosome 'HiC_scaffold_4' bin size 100000 stat - RD parity distribution gaussian fit:  38785.78 +- 3667.03
2022-09-28 16:49:54,762 - cnvpytor.root - INFO - Chromosome 'HiC_scaffold_4' bin size 100000 stat - RD unique distribution gaussian fit:  37383.33 +- 4053.49
2022-09-28 16:49:54,763 - cnvpytor.root - INFO - Calculating histograms using bin size 100000 for chromosome 'HiC_scaffold_5'.
2022-09-28 16:49:54,828 - cnvpytor.root - INFO - Chromosome 'HiC_scaffold_5' bin size 100000 stat - RD parity distribution gaussian fit:  40424.92 +- 4218.61
2022-09-28 16:49:54,829 - cnvpytor.root - INFO - Chromosome 'HiC_scaffold_5' bin size 100000 stat - RD unique distribution gaussian fit:  38801.85 +- 4688.61
2022-09-28 16:49:54,829 - cnvpytor.root - INFO - Calculating histograms using bin size 100000 for chromosome 'HiC_scaffold_6'.
2022-09-28 16:49:54,893 - cnvpytor.root - INFO - Chromosome 'HiC_scaffold_6' bin size 100000 stat - RD parity distribution gaussian fit:  40830.29 +- 4082.31
2022-09-28 16:49:54,893 - cnvpytor.root - INFO - Chromosome 'HiC_scaffold_6' bin size 100000 stat - RD unique distribution gaussian fit:  38895.00 +- 4660.91
2022-09-28 16:49:54,894 - cnvpytor.root - INFO - Calculating global statistics.
2022-09-28 16:49:54,899 - cnvpytor.root - INFO - Calculating GC corrected RD histogram using bin size 100000 for chromosome 'HiC_scaffold_1'.
Traceback (most recent call last):
  File "/nobackup/beegfs/home/ISAD/bh471/.local/bin/cnvpytor", line 8, in <module>
    sys.exit(main())
  File "/nobackup/beegfs/home/ISAD/bh471/.local/lib/python3.7/site-packages/cnvpytor/__main__.py", line 372, in main
    app.calculate_histograms(args.his, chroms=args.chrom)
  File "/nobackup/beegfs/home/ISAD/bh471/.local/lib/python3.7/site-packages/cnvpytor/root.py", line 902, in calculate_histograms
    his_p_corr = his_p / np.array(list(map(lambda x: gc_corr[int(x)], gcp_decompress(gcat, bin_ratio))))
  File "/nobackup/beegfs/home/ISAD/bh471/.local/lib/python3.7/site-packages/cnvpytor/root.py", line 902, in <lambda>
    his_p_corr = his_p / np.array(list(map(lambda x: gc_corr[int(x)], gcp_decompress(gcat, bin_ratio))))
IndexError: list index out of range
2022-09-28 16:49:56,236 - cnvpytor.genome - INFO - Reading configuration file '/nobackup/beegfs/workspace/bh471/scripts/ma_imi/cnvpytor/mper_ns_ref_genome_conf.py'.
2022-09-28 16:49:56,238 - cnvpytor.genome - INFO - Importing reference genome data: 'mpns'.
2022-09-28 16:49:56,246 - cnvpytor.root - INFO - Reference genome 'mpns' found in database.
2022-09-28 16:49:56,248 - cnvpytor.root - INFO - GC content for reference genome 'mpns' found in database.
2022-09-28 16:49:57,427 - cnvpytor.genome - INFO - Reading configuration file '/nobackup/beegfs/workspace/bh471/scripts/ma_imi/cnvpytor/mper_ns_ref_genome_conf.py'.
2022-09-28 16:49:57,428 - cnvpytor.genome - INFO - Importing reference genome data: 'mpns'.

```

**Comment by suvakov** [comment]
It is hard to reproduce this bug without `.pytor` file. Can you share it with us (you can mail me on suvakov at gmail)? 
Thanks

**Comment by bjhunt-git** [comment]
> 

Hello again, happy to report that I seem to have resolved this issue. I reformatted my genome FASTA file in two ways:

1) I simplified the chromosome/contig headers to numbers, ie simply 0, 1, 2, 3 and so on for each one.
2) I removed the line breaks on the sequences - the file as originally created had line breaks every 60 bases, I removed these so each chromosome/contig sequence is a single line.

I'm not sure which of these changes did the job (I suspect no. 2) but it's now running and generating CNV call files. I did email the .pytor file over to you but please disregard now. Many thanks for taking the time to look.
