### ISSUE TITLE
joint caller (prototype) error

### ISSUE THREAD

**Issue by wushyer** [abyzovlab/CNVpytor#161]
Hi, could you help me check this error?? Thanks
cnvpytor -conf ./example_ref_genome_conf.py -root file.pytor -call combined 10000 > calls.combined.10000.tsv
2023-01-19 17:36:29,042 - cnvpytor.genome - INFO - Reading configuration file './example_ref_genome_conf.py'.
2023-01-19 17:36:29,043 - cnvpytor.genome - INFO - Importing reference genome data: 'Tak'.
2023-01-19 17:36:29,083 - cnvpytor.root - WARNING - No bins with BAF=0.5! Using all bins for RD normalisation.
Traceback (most recent call last):
  File "/users/shuangyang.wu/miniconda3/envs/tools3/bin/cnvpytor", line 8, in <module>
    sys.exit(main())
  File "/users/shuangyang.wu/miniconda3/envs/tools3/lib/python3.7/site-packages/cnvpytor/__main__.py", line 434, in main
    use_hom=args.use_hom, anim=args.animation)
  File "/users/shuangyang.wu/miniconda3/envs/tools3/lib/python3.7/site-packages/cnvpytor/root.py", line 3127, in call_2d
    dmin = np.min(data)
  File "<__array_function__ internals>", line 6, in amin
  File "/users/shuangyang.wu/miniconda3/envs/tools3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2880, in amin
    keepdims=keepdims, initial=initial, where=where)
  File "/users/shuangyang.wu/miniconda3/envs/tools3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity

**Comment by lunalvan** [comment]
Hi, did any of you figure out how to solve this problem? I have the exact same thing myself.
I followed these steps:

``` 

cnvpytor -root file.pytor -rd ${BAM}
cnvpytor -root file.pytor -his ${BIN_SIZE}
cnvpytor -root file.pytor -snp ${VCF}
cnvpytor -root file.pytor -mask_snps
cnvpytor -root file.pytor -baf ${BIN_SIZE}
cnvpytor -root file.pytor -call combined ${BIN_SIZE} > file.cnvpytor.tsv

```

All the ${...} variables have been properly defined beforehand, so the error is not coming from those.

**Comment by wushyer** [comment]
Hi all, I didn't solve this. I am using another tool instead

**Comment by lunalvan** [comment]
Hi, I finally solved it!

I explained it a bit better here (https://github.com/abyzovlab/CNVpytor/issues/167), but for me the problem was with the FILTER column of the .vcf file. I added "-nofilter" to the -snp step to ignore that column and it worked.
