### ISSUE TITLE
Circular plot error

### ISSUE THREAD

**Issue by evayfang2019** [abyzovlab/CNVpytor#203]
It reports an error when running the script of **Circular plot**, but there is no error in **Manhattan plot** and **Region plot.**
 
###  script
```shell
## Call CNVs using read depth:
cnvpytor -root ./${kid}/cnv/kid.pytor \
    -rd ./${kid}/03.aligned/${kid}.aligned.sort.bam
cnvpytor -root ./${kid}/cnv/kid.pytor \
    -his 1000 10000 50000 100000 1000000
cnvpytor -root ./${kid}/cnv/kid.pytor \
    -partition 1000 10000 50000 100000 1000000
cnvpytor -root ./${kid}/cnv/kid.pytor \
    -call 1000 10000 50000 100000 1000000

## Importing and using single nucleotide polymorphism data:
cnvpytor -root ./${kid}/cnv/kid.pytor \
    -snp ./${kid}/08.deepvariant/${kid}.minimap2.dpv.vcf.gz
cnvpytor -root ./${kid}/cnv/kid.pytor \
    -pileup ./${kid}/03.aligned/${kid}.aligned.sort.bam
cnvpytor -root ./${kid}/cnv/kid.pytor -mask_snps
cnvpytor -root ./${kid}/cnv/kid.pytor -baf 1000 10000 50000 100000 1000000

# Genotyping with additional informations:
cnvpytor -root ./${kid}/cnv/kid.pytor -genotype 1000 10000 50000 100000 1000000 -a

#Circular plot
cnvpytor -root ./${kid}/cnv/${kid}.pytor -view 100000
cnvpytor> set style bmh
cnvpytor> set rd_use_mask
cnvpytor> set file_titles kid
cnvpytor> circular
```

### reports 
```
Traceback (most recent call last):
  File "/share/home/user/.local/lib/python3.10/site-packages/cnvpytor/viewer.py", line 521, in prompt
    self.parse(f + [str(self.bin_size)])
  File "/share/home/user/.local/lib/python3.10/site-packages/cnvpytor/viewer.py", line 390, in parse
    self.circular()
  File "/share/home/user/.local/lib/python3.10/site-packages/cnvpytor/viewer.py", line 2824, in circular
    np.warnings.filterwarnings('ignore')
  File "/share/home/user/miniconda3/envs/pacbio/lib/python3.10/site-packages/numpy/__init__.py", line 328, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'warnings'
```

numpy version=1.25.2

**Comment by evayfang2019** [comment]
Sorry, I solved the problem by reinstalling numpy v1.23.0
