### ISSUE TITLE
 rest.ensembl.org connect error

### ISSUE THREAD

**Issue by jeffchen2000** [abyzovlab/CNVpytor#218]
hi 

I got rest.ensembl.org connect error, not sure why this step is needed.
I believe this error is coming after our IT increasing our server security and disabled outside connection, but is there any way that I can get around of it?

thanks
Jeff C

Traceback (most recent call last):
  File "/miniconda3/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/miniconda3/lib/python3.11/site-packages/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/miniconda3/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='rest.ensembl.org', port=443): Max retries exceeded with url: /overlap/region/human/chr1:120200001-121000000?content-type=application/json;feature=gene; (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x154e428464d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

**Comment by arpanda** [comment]
I think, you have enabled the `set annotate` option, which identifies genes overlapping a CNV region using Ensembl. This is an optional step and can be performed separately as well.

You can either skip the `set annotate` part or run `unset annotate` to disable it.

Thank you,
Arijit

**Comment by jeffchen2000** [comment]
Hi Arijit
thanks for quick response.
yes, I used "set annotation".
but we have large number of samples, I have previously processed most of them with "set annotation". if I skip annotation with these samples and annotate them later, how can I ensure the annotation (reference used etc.) will be the same.

**Comment by arpanda** [comment]
How did you save your results ? Usually, the `set annotation` adds columns for genes names overlapping a CNV region. One can take those CNV region and find the overlapping genes.
  
Otherwise, the reference genome is already stored in the pytor file, it can be used later as well.
