### ISSUE TITLE
Other reference genome

### ISSUE THREAD

**Issue by gevro** [abyzovlab/CNVpytor#23]
Hi,
Is it possible to use CNVpytor with other reference genomes? There is no specific configuration parameters for this, so I assumed it would (I am trying CHM13_v1). However, when I make the root file and try to plot, I'm getting these errors:

```
2021-01-15 18:56:03,829 - cnvpytor.viewer - WARNING - Missing reference genome required for manhattan.

/gpfs/home/evrong01/.local/lib/python3.6/site-packages/cnvpytor/viewer.py:1284: UserWarning: Attempting to set identical bottom == top == 0 results in singular transformations; automatically expanding.
  ax.set_ylim([self.rd_range[0] * mean, self.rd_range[1] * mean / 2])
/gpfs/home/evrong01/.local/lib/python3.6/site-packages/cnvpytor/viewer.py:1286: UserWarning: Attempting to set identical left == right == -0.0 results in singular transformations; automatically expanding.
  ax.set_xlim([-l * 0.0, (l - 1) * 1.0])
Traceback (most recent call last):
  File "/gpfs/home/evrong01/.local/lib/python3.6/site-packages/cnvpytor/viewer.py", line 458, in prompt
    self.parse(f + [str(self.bin_size)])
  File "/gpfs/home/evrong01/.local/lib/python3.6/site-packages/cnvpytor/viewer.py", line 355, in parse
    self.multiple_regions(regions)
  File "/gpfs/home/evrong01/.local/lib/python3.6/site-packages/cnvpytor/viewer.py", line 1190, in multiple_regions
    self.regions(ix[i], r)
  File "/gpfs/home/evrong01/.local/lib/python3.6/site-packages/cnvpytor/viewer.py", line 1510, in regions
    ax.imshow(img, aspect='auto')
  File "/gpfs/home/evrong01/.local/lib/python3.6/site-packages/matplotlib/__init__.py", line 1565, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/gpfs/home/evrong01/.local/lib/python3.6/site-packages/matplotlib/cbook/deprecation.py", line 358, in wrapper
    return func(*args, **kwargs)
  File "/gpfs/home/evrong01/.local/lib/python3.6/site-packages/matplotlib/cbook/deprecation.py", line 358, in wrapper
    return func(*args, **kwargs)
  File "/gpfs/home/evrong01/.local/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 5615, in imshow
    im.set_data(X)
  File "/gpfs/home/evrong01/.local/lib/python3.6/site-packages/matplotlib/image.py", line 699, in set_data
    .format(self._A.shape))
TypeError: Invalid shape (0,) for image data
```

**Comment by gevro** [comment]
Oh, nevermind, I found this: https://github.com/abyzovlab/CNVpytor/blob/master/examples/AddReferenceGenome.md

**Comment by gevro** [comment]
Actually, I'm still having trouble. I made a configuration file. But I'm having these errors:

```
2021-01-15 19:36:46,363 - cnvpytor.genome - INFO - Reading configuration file '/gpfs/home/evrong01/evronylab/reference-files/CHM13_v1/CHM13_v1.pytorconf.py'.
2021-01-15 19:36:46,367 - cnvpytor.genome - INFO - Importing reference genome data: 'CHM13_v1'.
...
2021-01-15 19:36:46,481 - cnvpytor.bam - INFO - Detected reference genome: CHM13_v1
...
2021-01-15 19:51:16,190 - cnvpytor.root - INFO - Strict mask for reference genome 'CHM13_v1' found in database.
2021-01-15 19:51:16,192 - cnvpytor.io - ERROR - Unable to create file ~/evronylab/reference-files/CHM13_v1/CHM13_v1_mask_file.pytor!
2021-01-15 19:51:30,206 - cnvpytor.genome - INFO - Reading configuration file '/gpfs/home/evrong01/evronylab/reference-files/CHM13_v1/CHM13_v1.pytorconf.py'.
2021-01-15 19:51:30,213 - cnvpytor.genome - INFO - Importing reference genome data: 'CHM13_v1'.
2021-01-15 19:51:30,224 - cnvpytor.io - ERROR - Unable to open file ~/evronylab/reference-files/CHM13_v1/CHM13_v1_gc_file.pytor!
2021-01-15 19:51:32,212 - cnvpytor.genome - INFO - Reading configuration file '/gpfs/home/evrong01/evronylab/reference-files/CHM13_v1/CHM13_v1.pytorconf.py'.
2021-01-15 19:51:32,213 - cnvpytor.genome - INFO - Importing reference genome data: 'CHM13_v1'.
2021-01-15 19:51:32,216 - cnvpytor.io - ERROR - Unable to open file ~/evronylab/reference-files/CHM13_v1/CHM13_v1_gc_file.pytor!
2021-01-15 19:51:33,966 - cnvpytor.genome - INFO - Reading configuration file '/gpfs/home/evrong01/evronylab/reference-files/CHM13_v1/CHM13_v1.pytorconf.py'.
2021-01-15 19:51:33,967 - cnvpytor.genome - INFO - Importing reference genome data: 'CHM13_v1'.
2021-01-15 19:51:33,969 - cnvpytor.io - ERROR - Unable to open file ~/evronylab/reference-files/CHM13_v1/CHM13_v1_gc_file.pytor!
2021-01-15 19:51:35,718 - cnvpytor.genome - INFO - Reading configuration file '/gpfs/home/evrong01/evronylab/reference-files/CHM13_v1/CHM13_v1.pytorconf.py'.
2021-01-15 19:51:35,719 - cnvpytor.genome - INFO - Importing reference genome data: 'CHM13_v1'.
2021-01-15 19:51:35,722 - cnvpytor.io - ERROR - Unable to open file ~/evronylab/reference-files/CHM13_v1/CHM13_v1_gc_file.pytor!
2021-01-15 19:51:37,453 - cnvpytor.genome - INFO - Reading configuration file '/gpfs/home/evrong01/evronylab/reference-files/CHM13_v1/CHM13_v1.pytorconf.py'.
2021-01-15 19:51:37,454 - cnvpytor.genome - INFO - Importing reference genome data: 'CHM13_v1'.
2021-01-15 19:51:37,457 - cnvpytor.io - ERROR - Unable to open file ~/evronylab/reference-files/CHM13_v1/CHM13_v1_gc_file.pytor!
2021-01-15 19:51:39,199 - cnvpytor.genome - INFO - Reading configuration file '/gpfs/home/evrong01/evronylab/reference-files/CHM13_v1/CHM13_v1.pytorconf.py'.
2021-01-15 19:51:39,200 - cnvpytor.genome - INFO - Importing reference genome data: 'CHM13_v1'.
2021-01-15 19:51:39,202 - cnvpytor.io - ERROR - Unable to open file ~/evronylab/reference-files/CHM13_v1/CHM13_v1_gc_file.pytor!
2021-01-15 19:51:40,934 - cnvpytor.genome - INFO - Reading configuration file '/gpfs/home/evrong01/evronylab/reference-files/CHM13_v1/CHM13_v1.pytorconf.py'.
2021-01-15 19:51:40,935 - cnvpytor.genome - INFO - Importing reference genome data: 'CHM13_v1'.
2021-01-15 19:51:40,937 - cnvpytor.io - ERROR - Unable to open file ~/evronylab/reference-files/CHM13_v1/CHM13_v1_gc_file.pytor!
2021-01-15 19:51:42,660 - cnvpytor.genome - INFO - Reading configuration file '/gpfs/home/evrong01/evronylab/reference-files/CHM13_v1/CHM13_v1.pytorconf.py'.
2021-01-15 19:51:42,661 - cnvpytor.genome - INFO - Importing reference genome data: 'CHM13_v1'.
2021-01-15 19:51:42,665 - cnvpytor.io - ERROR - Unable to open file ~/evronylab/reference-files/CHM13_v1/CHM13_v1_gc_file.pytor!
...
2021-01-15 19:51:44,899 - cnvpytor.genome - INFO - Reading configuration file '/gpfs/home/evrong01/evronylab/reference-files/CHM13_v1/CHM13_v1.pytorconf.py'.
2021-01-15 19:51:44,900 - cnvpytor.genome - INFO - Importing reference genome data: 'CHM13_v1'.
2021-01-15 19:51:44,902 - cnvpytor.io - ERROR - Unable to open file ~/evronylab/reference-files/CHM13_v1/CHM13_v1_mask_file.pytor!
2021-01-15 19:51:46,644 - cnvpytor.genome - INFO - Reading configuration file '/gpfs/home/evrong01/evronylab/reference-files/CHM13_v1/CHM13_v1.pytorconf.py'.
2021-01-15 19:51:46,645 - cnvpytor.genome - INFO - Importing reference genome data: 'CHM13_v1'.
2021-01-15 19:51:46,647 - cnvpytor.io - ERROR - Unable to open file ~/evronylab/reference-files/CHM13_v1/CHM13_v1_mask_file.pytor!

```

So there is some issue with the configuration. But it is formatted per the instructions.

**Comment by gevro** [comment]
Fixed: Looks like the issue is using "~" in the path. Need the full path: /folder1/folder2/...
