### ISSUE TITLE
KeyError: 'chrNC_023642.1'

### ISSUE THREAD

**Issue by viplav97** [abyzovlab/CNVpytor#24]
My chromosome names are of the format NC_023642.1. When I try to run the command 
cnvpytor -conf Chlorocebus_sabaeus_genome_conf.py -root SRR6109149_aligned.pytor -rd SRR6109149_aligned.bam
I get the error KeyError: 'chrNC_023642.1'. My conf file is 

import_reference_genomes = {
    "cs1": {
        "name": "Chlorocebus_sabeus 1.1",
        "species": "Chlorocebus sabaeus",
        "chromosomes": OrderedDict(
            [("NC_023642.1", (126035930, "A")), ("NC_023643.1", (90373283, "A")), ("NC_023644.1", (92142175, "A")), ("NC_023645.1", (91010382, "A")), ("NC_023646.1", (75399963, "A")), ("NC_023647.1", (50890351, "A")), ("NC_023648.1", (135778131, "A")), ("NC_023649.1", (139301422, "A")), ("NC_023650.1", (125710982, "A")), ("NC_023651.1", (128595539, "A")), ("NC_023652.1", (128539186, "A")), ("NC_023653.1", (108555830, "A")),("NC_023654.1", (98384682, "A")),("NC_023655.1", (107702431, "A")),("NC_023656.1", (91754291, "A")), ("NC_023657.1", (75148670, "A")),("NC_023658.1", (71996105, "A")),("NC_023659.1", (72318688, "A")), ("NC_023660.1", (33263144, "A")), ("NC_023661.1", (130588469, "A")),("NC_023662.1", (127223203, "A")), ("NC_023663.1", (101219884, "A")), ("NC_023664.1", (82825804, "A")), ("NC_023665.1", (84932903, "A")), ("NC_023666.1", (85787240, "A")), ("NC_023667.1", (58131712, "A")),("NC_023668.1", (48547382, "A")), ("NC_023669.1", (21531802, "A")), ("NC_023670.1", (24206276, "A")), ("NC_023671.1", (130038232, "S")), ("NC_023672.1", (6181219, "S")), ("NC_008066.1", (16550, "M"))]),
        "gc_file":"/home/viplav/CNVanalysis/gc_file.pytor",
    }
}

Thanks in advance!

**Comment by suvakov** [comment]
Can you please run it again with "-v debug" option and send us output. Thanks

**Comment by PeterMulhair** [comment]
Hi,

Wondering if you have any updates on this issue? I've run into the same problem running:
cnvpytor -conf conf.py -root Pstr_genome.pytor -rd ../Parapoynx_stratiotata_prim_5fastq.bam -chrom tig00000042 -v debug

```bash
2021-02-04 19:30:27,303 - cnvpytor - DEBUG - Start logging...
2021-02-04 19:30:27,303 - cnvpytor.genome - DEBUG - Checking reference genome resource files.
2021-02-04 19:30:27,303 - cnvpytor.genome - INFO - Reading configuration file 'conf.py'.
2021-02-04 19:30:27,305 - cnvpytor.genome - INFO - Importing reference genome data: 'Pstr'.
2021-02-04 19:30:27,305 - cnvpytor.root - DEBUG - App class init: filename 'Pstr_genome.pytor'; max cores 8.
2021-02-04 19:30:27,305 - cnvpytor.io - DEBUG - Opening h5 file 'Pstr_genome.pytor'
2021-02-04 19:30:27,306 - cnvpytor.io - DEBUG - File 'Pstr_genome.pytor' successfully opened.
2021-02-04 19:30:27,315 - cnvpytor.bam - INFO - File: ../Parapoynx_stratiotata_prim_5fastq.bam successfully open
Traceback (most recent call last):
  File "/home/zoo/zool2500/miniconda3/bin/cnvpytor", line 8, in <module>
    sys.exit(main())
  File "/home/zoo/zool2500/miniconda3/lib/python3.7/site-packages/cnvpytor/__main__.py", line 214, in main
    app.rd(args.rd, chroms=args.chrom, reference_filename=args.reference_filename)
  File "/home/zoo/zool2500/miniconda3/lib/python3.7/site-packages/cnvpytor/root.py", line 295, in rd
    self._read_bam(bf, chroms, reference_filename=reference_filename, overwrite=overwrite)
  File "/home/zoo/zool2500/miniconda3/lib/python3.7/site-packages/cnvpytor/root.py", line 54, in _read_bam
    bamf = Bam(bf, reference_filename=reference_filename)
  File "/home/zoo/zool2500/miniconda3/lib/python3.7/site-packages/cnvpytor/bam.py", line 51, in __init__
    self.reference_genome = Genome.detect_genome(self.file.header.references, self.file.header.lengths)
  File "/home/zoo/zool2500/miniconda3/lib/python3.7/site-packages/cnvpytor/genome.py", line 247, in detect_genome
    found = found and (cls.reference_genomes[g]["chromosomes"][cls.extended_chrom_name(c)][0] == l)
KeyError: 'chrTIG00000001'
2021-02-04 19:30:27,342 - cnvpytor.io - DEBUG - Closing h5 file 'Pstr_genome.pytor'
```

Chromosome name should be tig00000001

The error looks the same as @viplav97's issue.

Thanks in advance for the help

**Comment by suvakov** [comment]
Please check now. Thank you for reporting.

**Comment by PeterMulhair** [comment]
Hi, thanks for fixing this. It now works perfectly for me.

**Comment by suvakov** [comment]
Great. Thanks for feedback.
