### ISSUE TITLE
Unable to create ROOT file

### ISSUE THREAD

**Issue by s-kumarswi** [abyzovlab/CNVpytor#243]
I am facing this error while creating the root file for a BAM file and reference FASTA. kindly help with the same 

The Error message :
```
Traceback (most recent call last):
  File "/home/swi/.local/bin/cnvpytor", line 33, in <module>
    sys.exit(load_entry_point('CNVpytor==1.3.2', 'console_scripts', 'cnvpytor')())
  File "/home/swi/.local/lib/python3.10/site-packages/CNVpytor-1.3.2-py3.10.egg/cnvpytor/__main__.py", line 187, in main
  File "/home/swi/.local/lib/python3.10/site-packages/CNVpytor-1.3.2-py3.10.egg/cnvpytor/genome.py", line 166, in check_resources
  File "/usr/lib/python3.10/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not Path

```
The Command I am using :
```
cnvpytor -root /home/swi/data/joshua/CNV-new/pecan/PECAN_calling/src/results/CNVPYTOR/2wgs.root -chrom chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22 chrX chrY  -rd /home/swi/data/joshua/CNV-new/2wgs_recal_reads.bam -j 16 -rg /mount/betastorefruz/beta-fs/gva_system/fastqdata/hg19/hg19.fasta
```
Thanks in Advance

**Comment by arpanda** [comment]
Hi @s-kumarswi ,

The issue is caused by the `-rg` parameter. CNVpytor already includes the reference genome for `hg19`, so there's no need to specify a reference genome path. It will automatically detect the reference genome. 

Try running it without the `-rg` option.
```
cnvpytor -root /home/swi/data/joshua/CNV-new/pecan/PECAN_calling/src/results/CNVPYTOR/2wgs.pytor -rd /home/swi/data/joshua/CNV-new/2wgs_recal_reads.bam -j 16
```
or 

```
cnvpytor -root /home/swi/data/joshua/CNV-new/pecan/PECAN_calling/src/results/CNVPYTOR/2wgs.pytor -chrom chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22 chrX chrY  -rd /home/swi/data/joshua/CNV-new/2wgs_recal_reads.bam -j 16 
```

-Thanks
Arijit
