### ISSUE TITLE
Error running cnvpytor

### ISSUE THREAD

**Issue by xiaohuli-45** [abyzovlab/CNVpytor#244]
Hello! I successfully used cnvpytor a few months ago, but recently I encountered the following error:
```
2024-11-13 09:26:56,809 - cnvpytor-ERROR - Some reference genome resource files are missing. Run 'cnvpytor-download' as same user who has installed cnvpytor.
```
I run `cnvpytor-download` and the following error occurs:
```
2024-11-13 09:42:28,904 - cnvpytor.genome - INFO - Updating reference genome resource files...
2024-11-13 09:42:28,904 - cnvpytor.genome - INFO - Detecting missing GC resource file for reference genome 'hg19'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 421, in connect
    tls_in_tls=tls_in_tls,
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 429, in ssl_wrap_socket
    sock, context, tls_in_tls, server_hostname=server_hostname
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib64/python3.6/ssl.py", line 365, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib64/python3.6/ssl.py", line 776, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1036, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 648, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:877)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError
```
I don't quite understand the reason, could you tell me how to solve the problem? 

Thank you

**Comment by arpanda** [comment]
Hi @xiaohuli-45 ,
The `cnvpytor-download` command tries to download reference genome files from GitHub. This step is failing, most likely due to some network-related issues. 

Another approach is to install directly from GitHub. This method doesn't require `cnvpytor-download`, as the reference genome files are already included during the installation. Here’s the command to install it:

```
pip install git+https://github.com/abyzovlab/CNVpytor.git
``

Thanks
Arijit

**Comment by xiaohuli-45** [comment]
Thank you, I can use it normally after reinstalling it with the command you gave
