### ISSUE TITLE
Error: only integer scalar arrays can be converted to a scalar index

### ISSUE THREAD

**Issue by NinaGerrekens** [abyzovlab/CNVpytor#248]
Hi,
I have installed CNVpytor directly from GitHub and made CNV calls using the following commands:
```
cnvpytor -root file1.root -rd inputfile.bam -chrom $(seq -f 'chr%g' 1 22) chrX chrY
cnvpytor -root file1.root -his 1000 10000 100000
cnvpytor -root file1.root -partition 1000 10000 100000
cnvpytor -root file1.root -call 1000 10000 100000
```

When I try to generate a compare plot for a sample in the interactive viewer using the following commands: 
```
cnvpytor -root file1.root -view 10000
    cnvpytor> set bin_size 10000
    cnvpytor> set style classic
    cnvpytor> set rd_use_mask
    cnvpytor> set plot
    cnvpytor> compare 16:5400k-6200k 16:17500k-18200k
```

I get the following error: 
```
Traceback (most recent call last):
  File "/sc/arion/work/gerren01/miniconda3/envs/cnvpytor_1.3.1/bin/cnvpytor", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/sc/arion/work/gerren01/miniconda3/envs/cnvpytor_1.3.1/lib/python3.12/site-packages/cnvpytor/__main__.py", line 331, in main
    view.prompt()
  File "/sc/arion/work/gerren01/miniconda3/envs/cnvpytor_1.3.1/lib/python3.12/site-packages/cnvpytor/viewer.py", line 497, in prompt
    self.compare(f[1], f[2], plot=self.plot)
  File "/sc/arion/work/gerren01/miniconda3/envs/cnvpytor_1.3.1/lib/python3.12/site-packages/cnvpytor/viewer.py", line 3136, in compare
    data1 += list(his_p[bin1:bin2 + 1][np.isfinite(his_p[bin1:bin2 + 1])])
                  ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: only integer scalar arrays can be converted to a scalar index
```
I have also tried to use different bin sizes, using the following format for the comparison:16:5400000-6200000 16:17500000-18200000 and comparing different regions, but I keep getting the error.

Thank you in advance for your help!

**Comment by NinaGerrekens** [comment]
The issue was solved by adding "chr" as a prefix.
