### ISSUE TITLE
Persistent Issue After Indexing BAM and Reference

### ISSUE THREAD

**Issue by prabirbioinfo** [abyzovlab/CNVpytor#249]
### After indexing the BAM file and reference.fasta, and adjusting the memory configuration, the same issue persists...

1.> **cnvpytor -root file.pytor -chrom A03 -his 1000 10000 100000 -T /media/ppeb/4tb_drive/Bju.genome.fasta**
2024-12-26 12:21:41,424 - cnvpytor.root - INFO - Calculating global statistics.
2024-12-26 12:21:41,427 - cnvpytor.root - INFO - Calculating global statistics.
2024-12-26 12:21:41,430 - cnvpytor.root - INFO - Calculating global statistics.

2.>**cnvpytor -root file.pytor -chrom A03 -his 1000 10000 100000 -T /media/ppeb/4tb_drive/Bju.genome.fasta -v debug -log cnvpytor_run.log -j 1**
2024-12-26 12:27:28,185 - cnvpytor - DEBUG - Start logging...
2024-12-26 12:27:28,185 - cnvpytor.genome - DEBUG - Checking reference genome resource files.
2024-12-26 12:27:28,185 - cnvpytor.root - DEBUG - App class init: filename 'file.pytor'; max cores 1.
2024-12-26 12:27:28,185 - cnvpytor.io - DEBUG - Opening h5 file 'file.pytor'
2024-12-26 12:27:28,186 - cnvpytor.io - DEBUG - File 'file.pytor' successfully opened.
2024-12-26 12:27:28,192 - cnvpytor.root - INFO - Calculating global statistics.
2024-12-26 12:27:28,194 - cnvpytor.root - INFO - Calculating global statistics.
2024-12-26 12:27:28,197 - cnvpytor.root - INFO - Calculating global statistics.
2024-12-26 12:27:28,199 - cnvpytor.io - DEBUG - Closing h5 file 'file.pytor'

**Comment by suvakov** [comment]
Did you configure the reference genome as described in the [example](https://github.com/abyzovlab/CNVpytor/blob/master/examples/AddReferenceGenome.md)? 

Btw, the option `-T fasta_file` here does not have an effect. It should only be used for reading the CRAM file in the `-rd` step.

**Comment by prabirbioinfo** [comment]
_Thank you for your reply! Let me clarify my process from the beginning:_

1. I indexed my input `sorted.bam`.
2. I used a compressed, indexed reference genome file.
3. Configured by CNVpytor with the command:  
   `cnvpytor -root bju_gc_file.pytor -gc bju.genome.fasta.gz -make_gc_file`.
4. Successfully created `bju_gc_file.pytor` (though it’s a binary file, so I can't open it directly).
5. Ensured all files have the necessary permissions to access.
6. Ran CNVpytor with:  
   `cnvpytor -root b_output.pytor -gc bju_gc.pytor -rd 10.sorted.bam -make_gc_file`.

However, after running it a few times, I encountered the following error:  
`[E::fai_build_core] Format error, unexpected character at line 1`  
`[ERROR] Problem opening file 'bju_gc.pytor'`.

Can you help me solve this issue? I'd appreciate any advice.

**Comment by arpanda** [comment]
Hi @prabirbioinfo ,
Looks like, you have not configured your reference genome . The gc file should be in the configuration file. 

An example reference configuration  file; 

```
# example_ref_genome_conf.py
import_reference_genomes = {
    "mm9": {
        "name": "MGSCv37",
        "species": "Mus musculus",
        "chromosomes": OrderedDict(
            [("chr1", (197195432, "A")), ("chr2", (181748087, "A")), ("chr3", (159599783, "A")),
            ("chr4", (155630120, "A")), ("chr5", (152537259, "A")), ("chr6", (149517037, "A")),
            ("chr7", (152524553, "A")), ("chr8", (131738871, "A")), ("chr9", (124076172, "A")),
            ("chr10", (129993255, "A")), ("chr11", (121843856, "A")), ("chr12", (121257530, "A")),
            ("chr13", (120284312, "A")), ("chr14", (125194864, "A")), ("chr15", (103494974, "A")),
            ("chr16", (98319150, "A")), ("chr17", (95272651, "A")), ("chr18", (90772031, "A")),
            ("chr19", (61342430, "A")), ("chrX", (166650296, "S")), ("chrY", (15902555, "S")),
            ("chrM", (16299, "M"))]),
        "gc_file":"/..PATH../MGSCv37_gc_file.pytor",
        "mask_file": "/..PATH../MGSCv37_mask_file.pytor"
    }
}
```
The above file can be used in cnvpytor file using `-conf` parameter.
```
cnvpytor -conf REL_PATH/example_ref_genome_conf.py -root file.pytor -rd file.bam
```
For details please visit: https://github.com/abyzovlab/CNVpytor/blob/master/examples/AddReferenceGenome.md

**Comment by prabirbioinfo** [comment]
The issue seems to be that the reference file has not been properly configured in the example_ref_genome_conf.py, and the reference name (Bju) cannot be found in the file.pytor file. This mismatch in naming between the example.py file and the configured reference is causing the problem. Proper configuration is required to resolve this.
error- Traceback (most recent call last):
  File "/home/ppeb/.local/bin/cnvpytor", line 8, in <module>
    sys.exit(main())
  File "/home/ppeb/.local/lib/python3.10/site-packages/cnvpytor/__main__.py", line 298, in main
    app.rd(args.rd, chroms=args.chrom, reference_filename=args.reference_filename)
  File "/home/ppeb/.local/lib/python3.10/site-packages/cnvpytor/root.py", line 407, in rd
    if "mask_file" in Genome.reference_genomes[rg_name]:
KeyError: 'Bju'
code- cnvpytor -conf example_ref_genome_conf.py -root FILE2.pyter -rd 10.sorted.bam

#i attached example_ref_genome_conf.py
[example_ref_genome_conf.zip](https://github.com/user-attachments/files/18407061/example_ref_genome_conf.zip)
@arpanda @suvakov
