### ISSUE TITLE
Processes are defunct

### ISSUE THREAD

**Issue by james-guevara** [abyzovlab/CNVpytor#26]
Hi I ran this cnvpytor command:

```
cnvpytor -root results-cnvpytor/input.pytor -rd data/input.cram -T reference/GRCh38_full_analysis_set_plus_decoy_hla.fa
```

Here is the output:
```
2021-02-19 04:53:06,110 - cnvpytor.bam - INFO - File: data/input.cram successfully open
2021-02-19 04:53:06,117 - cnvpytor.bam - INFO - Detected reference genome: hg38
2021-02-19 04:53:06,226 - cnvpytor.pool - INFO - Parallel processing using 8 cores
2021-02-19 04:53:06,413 - cnvpytor.root - INFO - Reading data for chromosome chr1 with length 248956422
2021-02-19 04:53:06,413 - cnvpytor.root - INFO - Reading data for chromosome chr2 with length 242193529
2021-02-19 04:53:06,413 - cnvpytor.root - INFO - Reading data for chromosome chr3 with length 198295559
2021-02-19 04:53:06,413 - cnvpytor.root - INFO - Reading data for chromosome chr4 with length 190214555
2021-02-19 04:53:06,413 - cnvpytor.root - INFO - Reading data for chromosome chr5 with length 181538259
2021-02-19 04:53:06,413 - cnvpytor.root - INFO - Reading data for chromosome chr6 with length 170805979
2021-02-19 04:53:06,413 - cnvpytor.root - INFO - Reading data for chromosome chr7 with length 159345973
2021-02-19 04:53:06,415 - cnvpytor.root - INFO - Reading data for chromosome chr8 with length 145138636
2021-02-19 04:55:35,376 - cnvpytor.root - INFO - Reading data for chromosome chr9 with length 138394717
...
2021-02-19 05:00:00,475 - cnvpytor.root - INFO - Reading data for chromosome HLA-DRB1*15:01:01:04 with length 11056
2021-02-19 05:00:00,484 - cnvpytor.root - INFO - Reading data for chromosome HLA-DRB1*15:02:01 with length 10313
2021-02-19 05:00:00,494 - cnvpytor.root - INFO - Reading data for chromosome HLA-DRB1*15:03:01:01 with length 11567
2021-02-19 05:00:00,494 - cnvpytor.root - INFO - Reading data for chromosome HLA-DRB1*15:03:01:02 with length 11569
2021-02-19 05:00:00,494 - cnvpytor.root - INFO - Reading data for chromosome HLA-DRB1*16:02:01 with length 11005
```

But the process hadn't stopped, so I checked the processes with the `ps` command, and here's what it showed:

```
  PID TTY          TIME CMD
 8219 pts/0    00:00:00 bash
18312 pts/0    00:00:27 cnvpytor
18329 pts/0    00:06:52 cnvpytor <defunct>
18330 pts/0    00:08:17 cnvpytor <defunct>
18331 pts/0    00:06:53 cnvpytor <defunct>
18332 pts/0    00:06:52 cnvpytor <defunct>
18333 pts/0    00:06:49 cnvpytor <defunct>
18334 pts/0    00:06:50 cnvpytor <defunct>
18335 pts/0    00:06:51 cnvpytor <defunct>
18336 pts/0    00:06:49 cnvpytor <defunct>
23461 pts/0    00:00:00 ps
```

I'm wondering why the processes are defunct and if that's a problem (perhaps on my end)? From what I understand, this means that the parent process has not destroyed these processes properly. Also wondering if it's safe to assume that the program finished despite these defunct processes.

EDIT: Also, here's the traceback:

```
Traceback (most recent call last):
  File "/home/j3guevar/anaconda3/envs/env_cnvpytor/bin/cnvpytor", line 11, in <module>
    sys.exit(main())
  File "/home/j3guevar/anaconda3/envs/env_cnvpytor/lib/python3.7/site-packages/cnvpytor/__main__.py", line 209, in main
    app.rd(args.rd, chroms=args.chrom, reference_filename=args.reference_filename)
  File "/home/j3guevar/anaconda3/envs/env_cnvpytor/lib/python3.7/site-packages/cnvpytor/root.py", line 293, in rd
    self._read_bam(bf, chroms, reference_filename=reference_filename, overwrite=overwrite)
  File "/home/j3guevar/anaconda3/envs/env_cnvpytor/lib/python3.7/site-packages/cnvpytor/root.py", line 87, in _read_bam
    res = parmap(read_chromosome, chr_len, cores=self.max_cores)
  File "/home/j3guevar/anaconda3/envs/env_cnvpytor/lib/python3.7/site-packages/cnvpytor/pool.py", line 52, in parmap
    res = [q_out.get() for _ in range(len(sent))]
  File "/home/j3guevar/anaconda3/envs/env_cnvpytor/lib/python3.7/site-packages/cnvpytor/pool.py", line 52, in <listcomp>
    res = [q_out.get() for _ in range(len(sent))]
  File "/home/j3guevar/anaconda3/envs/env_cnvpytor/lib/python3.7/multiprocessing/queues.py", line 94, in get
    res = self._recv_bytes()
  File "/home/j3guevar/anaconda3/envs/env_cnvpytor/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/j3guevar/anaconda3/envs/env_cnvpytor/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/j3guevar/anaconda3/envs/env_cnvpytor/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
```

EDIT: Sorry should've checked the input.pytor file, which looks incomplete:
```
cnvpytor -root input.pytor -ls

Filename 'input.pytor'
--------------------------
File created: 2021-02-19 04:53 using CNVpytor ver 1.0

Chromosomes with RD signal: 

Chromosomes with SNP signal: 

Using reference genome: hg38 [ GC: yes, mask: yes ]

Chromosomes with RD histograms [bin sizes]:  []

Chromosomes with SNP histograms [bin sizes]:  []

Chromosome lengths: {}
```

**Comment by james-guevara** [comment]
Actually, things seem to run to completion if I just restrict the program to the standard autosomes and sex chromosomes.

**Comment by suvakov** [comment]
Some contings probably were not present in reference genome fasta and cram parsing got stuck . Thanks
