### ISSUE TITLE
Error with gzipped VCF files

### ISSUE THREAD

**Issue by gevro** [abyzovlab/CNVpytor#3]
Hi,
Trying to run -vcf with a .gz vcf files gives an error:
Traceback (most recent call last):
  File "/miniconda/bin/cnvpytor", line 10, in <module>
    sys.exit(main())
  File "/miniconda/lib/python2.7/site-packages/cnvpytor/__main__.py", line 242, in main
    ad_tag=args.ad_tag, gt_tag=args.gt_tag)
  File "/miniconda/lib/python2.7/site-packages/cnvpytor/root.py", line 327, in vcf
    callset=callset, use_index=use_index)
  File "/miniconda/lib/python2.7/site-packages/cnvpytor/root.py", line 235, in _read_vcf
    vcff = Vcf(vcf_file)
  File "/miniconda/lib/python2.7/site-packages/cnvpytor/vcf.py", line 27, in __init__
    self.file = pysam.VariantFile(filename)
  File "pysam/libcbcf.pyx", line 4036, in pysam.libcbcf.VariantFile.__init__
  File "pysam/libcbcf.pyx", line 4299, in pysam.libcbcf.VariantFile.open
  File "pysam/libchtslib.pyx", line 518, in pysam.libchtslib.HTSFile.tell
NotImplementedError: seek not implemented in files compressed by method 1

**Comment by suvakov** [comment]
This is pysam error. Think this is one discussed here:
https://github.com/pysam-developers/pysam/issues/536
