### ISSUE TITLE
Trouble with new reference genome

### ISSUE THREAD

**Issue by wbooker** [abyzovlab/CNVpytor#34]
Hi,

I have been able previously to get cnvpytor calling SVs with a non-human reference, but for some reason trying to do so with this new reference and bam files, I am unable to generate histograms and proceed from there. Any help you can give so I can figure out why this isn't working would be great! 

my conf file:
```
import_reference_genomes = {
     "VectorBase-50_AaegyptiLVP_AGWG_Genome": {
		"name": "Aaegypti",
		"species": "Aedes aegypti",
		"chromosomes": OrderedDict(
			[("AaegL5_1", (310827022, "A")), ("AaegL5_2", (474425716, "A")), 
			("AaegL5_3", (409777670, "A")), ("AaegL5_MT", (16790, "M"))]),
		"gc_file":"Aaegypti_gcFile.pytor"
	}
}
```

and script for this data (running in nextflow so has variables for files, also not working running on its own for a test file):
```
cnvpytor -root "${bamfile.baseName}.pytor" -conf $conf -chrom AaegL5_1 AaegL5_2 AaegL5_3 AaegL5_MT -rd $bamfile 
cnvpytor -root "${bamfile.baseName}.pytor" -conf $conf -rg VectorBase-50_AaegyptiLVP_AGWG_Genome
cnvpytor -root "${bamfile.baseName}.pytor" -conf $conf -his 100
cnvpytor -root "${bamfile.baseName}.pytor" -conf $conf -partition 100
cnvpytor -root "${bamfile.baseName}.pytor" -conf $conf -call 100 > "${bamfile.baseName}.tsv"
```

I am able to generate the pytor file, but generating the histogram doesn't seem to work for any bin size.

using -ls, I get the following after -his

```
File created: 2021-03-30 18:27 using CNVpytor ver 1.0

Chromosomes with RD signal: AaegL5_1, AaegL5_2, AaegL5_3, AaegL5_MT

Chromosomes with SNP signal: 

Using reference genome: VectorBase-50_AaegyptiLVP_AGWG_Genome[ 
Chromosomes with RD histograms [bin sizes]:  []

Chromosomes with SNP histograms [bin sizes]:  []

Chromosome lengths: {'AaegL5_1': '310827022', 'AaegL5_2': '474425716', 'AaegL5_3': '409777670', 'AaegL5_MT': '16790'}
```

-his 100 produces this output:
```
2021-04-05 13:28:41,819 - cnvpytor.genome - INFO - Reading configuration file 'aegy_conf.py'.
2021-04-05 13:28:41,821 - cnvpytor.genome - INFO - Importing reference genome data: 'VectorBase-50_AaegyptiLVP_AGWG_Genome'.
2021-04-05 13:28:42,783 - cnvpytor.root - INFO - Calculating global statistics.
```

Thanks,
Will Booker

**Comment by arpanda** [comment]
By default, it stores the data for 100 bp histogram and calculates the other bins based on that.
So, can you please try with other bin size like 1000 or 10000. 

Thanks

**Comment by wbooker** [comment]
I get the same results whether trying 1000 or 10000

thanks
Will

**Comment by arpanda** [comment]
You are using CNVpytor version 1.0. In the meantime, we had several issues with contig names and we fixed some issues in the version 1.1 available on Github. Maybe your issue is solved in the this version 1.1.
Installation commands 
```
git clone https://github.com/abyzovlab/CNVpytor.git
cd CNVpytor
python setup.py install
```

Please let us know if its solve your issue or not. We appreciate your feedback. Thanks

**Comment by wbooker** [comment]
That worked for that part! Unfortunately now getting this error when generating the histograms. happens for all bin sizes and for the previously working dataset as well:

```
[wwbooker@c0501 wwbooker]$ cnvpytor -root Test1_1.pytor -conf aegy_conf.py -his 100000
2021-04-06 20:07:09,699 - cnvpytor.genome - INFO - Reading configuration file 'aegy_conf.py'.
2021-04-06 20:07:09,701 - cnvpytor.genome - INFO - Importing reference genome data: 'VectorBase-50_AaegyptiLVP_AGWG_Genome'.
2021-04-06 20:07:11,000 - cnvpytor.root - INFO - Calculating histograms using bin size 100000 for chromosome 'AaegL5_1'.
2021-04-06 20:07:11,333 - cnvpytor.root - INFO - Chromosome 'AaegL5_1' bin size 100000 stat - RD parity distribution gaussian fit:  17007.92 +- 4201.31
2021-04-06 20:07:11,333 - cnvpytor.root - INFO - Chromosome 'AaegL5_1' bin size 100000 stat - RD unique distribution gaussian fit:  11841.40 +- 3812.45
2021-04-06 20:07:11,333 - cnvpytor.root - INFO - Calculating histograms using bin size 100000 for chromosome 'AaegL5_2'.
2021-04-06 20:07:11,701 - cnvpytor.root - INFO - Chromosome 'AaegL5_2' bin size 100000 stat - RD parity distribution gaussian fit:  17424.24 +- 3947.92
2021-04-06 20:07:11,702 - cnvpytor.root - INFO - Chromosome 'AaegL5_2' bin size 100000 stat - RD unique distribution gaussian fit:  12628.70 +- 3685.29
2021-04-06 20:07:11,702 - cnvpytor.root - INFO - Calculating histograms using bin size 100000 for chromosome 'AaegL5_3'.
2021-04-06 20:07:12,017 - cnvpytor.root - INFO - Chromosome 'AaegL5_3' bin size 100000 stat - RD parity distribution gaussian fit:  17529.13 +- 3897.68
2021-04-06 20:07:12,017 - cnvpytor.root - INFO - Chromosome 'AaegL5_3' bin size 100000 stat - RD unique distribution gaussian fit:  12554.30 +- 3572.51
2021-04-06 20:07:12,017 - cnvpytor.root - INFO - Calculating histograms using bin size 100000 for chromosome 'AaegL5_MT'.
2021-04-06 20:07:12,106 - cnvpytor.root - INFO - Chromosome 'AaegL5_MT' bin size 100000 stat - RD parity distribution gaussian fit:  3870.00 +- 0.00
2021-04-06 20:07:12,106 - cnvpytor.root - INFO - Chromosome 'AaegL5_MT' bin size 100000 stat - RD unique distribution gaussian fit:  522.00 +- 0.00
2021-04-06 20:07:12,106 - cnvpytor.root - INFO - Calculating global statistics.
2021-04-06 20:07:12,115 - cnvpytor.root - INFO - Calculating GC corrected RD histogram using bin size 100000 for chromosome 'AaegL5_1'.
Traceback (most recent call last):
  File "/nas/longleaf/home/wwbooker/.local/bin/cnvpytor", line 11, in <module>
    load_entry_point('CNVpytor==1.1', 'console_scripts', 'cnvpytor')()
  File "/nas/longleaf/home/wwbooker/.local/lib/python3.7/site-packages/CNVpytor-1.1-py3.7.egg/cnvpytor/__main__.py", line 310, in main
  File "/nas/longleaf/home/wwbooker/.local/lib/python3.7/site-packages/CNVpytor-1.1-py3.7.egg/cnvpytor/root.py", line 829, in calculate_histograms
  File "/nas/longleaf/home/wwbooker/.local/lib/python3.7/site-packages/CNVpytor-1.1-py3.7.egg/cnvpytor/root.py", line 829, in <lambda>
IndexError: list index out of range
```

**Comment by suvakov** [comment]
It seems that something is wrong with GC correction. Do you have Aaegypti_gcFile.pytor in the same directory?

**Comment by suvakov** [comment]
Please try again after updating CNVpytor by cloning GitHub repository. We have bug related to chromosome classification. Thank you for reporting this. Please let us know does it work.

**Comment by wbooker** [comment]
That fix did the trick! Thanks so much.

**Comment by suvakov** [comment]
Thanks
