### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by gevro** [abyzovlab/CNVpytor#60]
Hi,
I'm getting this error every time I try to plot something:

```
Making cnvpytor plots...
   Genome-wide plots

    * rd_use_mask: False

   Chromosome plots
   chr1
Traceback (most recent call last):
  File "/gpfs/home/evrong01/.local/lib/python3.6/site-packages/cnvpytor/viewer.py", line 508, in prompt
    self.parse(f + [str(self.bin_size)])
  File "/gpfs/home/evrong01/.local/lib/python3.6/site-packages/cnvpytor/viewer.py", line 386, in parse
    self.multiple_regions(regions)
  File "/gpfs/home/evrong01/.local/lib/python3.6/site-packages/cnvpytor/viewer.py", line 1730, in multiple_regions
    self.regions(self.plot_files[i], r)
  File "/gpfs/home/evrong01/.local/lib/python3.6/site-packages/cnvpytor/viewer.py", line 2146, in regions
    l = img.shape[1]
IndexError: tuple index out of range

```

**Comment by gevro** [comment]
Note, this is likely a bug. Because chr1 is definitely in the root file:

```
--------------------------------------------
File created: 2021-09-03 17:11 using CNVpytor ver 1.1

Chromosomes with RD signal: chr1, chr2, chr3, chr4, chr5, chr6, chr7, chr8, chr9, chr10, chr11, chr12, chr13, chr14, chr15, chr16, chr17, chr18, chr19, chr20, chr21, chr22, chrX, chrY

Chromosomes with SNP signal: 

Using reference genome: hg38 [ GC: yes, mask: yes ]

Chromosomes with RD histograms [bin sizes]: chr10, chr11, chr12, chr13, chr14, chr15, chr16, chr17, chr18, chr19, chr1, chr20, chr21, chr22, chr2, chr3, chr4, chr5, chr6, chr7, chr8, chr9, chrX, chrY [1000, 10000, 100000]

Chromosomes with SNP histograms [bin sizes]:  []

Chromosome lengths: {'chr1': '248956422', 'chr2': '242193529', 'chr3': '198295559', 'chr4': '190214555', 'chr5': '181538259', 'chr6': '170805979', 'chr7': '159345973', 'chr8': '145138636', 'chr9': '138394717', 'chr10': '133797422', 'chr11': '135086622', 'chr12': '133275309', 'chr13': '114364328', 'chr14': '107043718', 'chr15': '101991189', 'chr16': '90338345', 'chr17': '83257441', 'chr18': '80373285', 'chr19': '58617616', 'chr20': '64444167', 'chr21': '46709983', 'chr22': '50818468', 'chrX': '156040895', 'chrY': '57227415'}
```

Here is a simple replication of the error:
```
$ cnvpytor -root file.root -view 10000
cnvpytor> set panels rd likelihood baf
    * panels: ['rd', 'likelihood', 'baf']
cnvpytor> set legend
    * legend: True
cnvpytor> set rd_use_mask
    * rd_use_mask: True
cnvpytor> chr1
Traceback (most recent call last):
  File "/gpfs/home/evrong01/.local/lib/python3.6/site-packages/cnvpytor/viewer.py", line 508, in prompt
    self.parse(f + [str(self.bin_size)])
  File "/gpfs/home/evrong01/.local/lib/python3.6/site-packages/cnvpytor/viewer.py", line 386, in parse
    self.multiple_regions(regions)
  File "/gpfs/home/evrong01/.local/lib/python3.6/site-packages/cnvpytor/viewer.py", line 1730, in multiple_regions
    self.regions(self.plot_files[i], r)
  File "/gpfs/home/evrong01/.local/lib/python3.6/site-packages/cnvpytor/viewer.py", line 2146, in regions
    l = img.shape[1]
IndexError: tuple index out of range
```

**Comment by gevro** [comment]
Some more details. It is generating it when I add likelihood to 'set panels'. Also, 'set panels baf' is giving a different error
```
$ cnvpytor -root TN-20-36_blood_skin.cnvpytor.root -view 10000
cnvpytor> set panels baf
    * panels: ['baf']
cnvpytor> chr1
/gpfs/home/evrong01/.local/lib/python3.6/site-packages/cnvpytor/viewer.py:2049: UserWarning: Attempting to set identical left == right == -0.0 results in singular transformations; automatically expanding.
  ax.set_xlim([-l * 0.0, (l - 1) * 1.0])
cnvpytor> set panels likelihood
    * panels: ['likelihood']
cnvpytor> chr1
Traceback (most recent call last):
  File "/gpfs/home/evrong01/.local/lib/python3.6/site-packages/cnvpytor/viewer.py", line 508, in prompt
    self.parse(f + [str(self.bin_size)])
  File "/gpfs/home/evrong01/.local/lib/python3.6/site-packages/cnvpytor/viewer.py", line 386, in parse
    self.multiple_regions(regions)
  File "/gpfs/home/evrong01/.local/lib/python3.6/site-packages/cnvpytor/viewer.py", line 1730, in multiple_regions
    self.regions(self.plot_files[i], r)
  File "/gpfs/home/evrong01/.local/lib/python3.6/site-packages/cnvpytor/viewer.py", line 2146, in regions
    l = img.shape[1]
IndexError: tuple index out of range

cnvpytor> set panels rd
    * panels: ['rd']
cnvpytor> chr1
```

**Comment by gevro** [comment]
Sorry, I found the problem! When I ran the -snp command, the -sample setting was set to a non-existent sample name.
