### ISSUE TITLE
An error occurred while importing SNP data.

### ISSUE THREAD

**Issue by m-rq** [abyzovlab/CNVpytor#62]
When I run
`cnvpytor -conf 1_ref_genome_conf.py -root root.pytor -snp Filter.vcf.gz -sample FJSA40.2`
or
`cnvpytor -root root.pytor -snp Filter.vcf.gz -sample FJSA40.2`

display
```
2021-09-04 16:33:28,773 - cnvpytor.genome - INFO - Reading configuration file '1_ref_genome_conf_auto.py'.
2021-09-04 16:33:28,908 - cnvpytor.genome - INFO - Importing reference genome data: 'sc'.
2021-09-04 16:33:28,912 - cnvpytor.vcf - INFO - File: Filter.vcf.gz successfully open
2021-09-04 16:33:28,912 - cnvpytor.root - INFO - Reading variant data for chromosome NC_001133.9
Traceback (most recent call last):
  File "/home/bioinfo/Private/mrq/bin/Anaconda3/envs/cnvpytor/bin/cnvpytor", line 8, in <module>
    sys.exit(main())
  File "/home/bioinfo/Private/mrq/bin/Anaconda3/envs/cnvpytor/lib/python3.7/site-packages/cnvpytor/__main__.py", line 284, in main
    ad_tag=args.ad_tag, gt_tag=args.gt_tag, filter=not args.no_filter)
  File "/home/bioinfo/Private/mrq/bin/Anaconda3/envs/cnvpytor/lib/python3.7/site-packages/cnvpytor/root.py", line 338, in vcf
    callset=callset, use_index=use_index)
  File "/home/bioinfo/Private/mrq/bin/Anaconda3/envs/cnvpytor/lib/python3.7/site-packages/cnvpytor/root.py", line 269, in _read_vcf
    gt_tag=gt_tag, filter=filter)
  File "/home/bioinfo/Private/mrq/bin/Anaconda3/envs/cnvpytor/lib/python3.7/site-packages/cnvpytor/vcf.py", line 162, in read_chromosome_snp
    gt.append(gt_from_list(rec.samples[sample][gt_tag], rec.samples[sample].phased))
  File "/home/bioinfo/Private/mrq/bin/Anaconda3/envs/cnvpytor/lib/python3.7/site-packages/cnvpytor/utils.py", line 779, in gt_from_list
    haps = list(map(int1, l))
  File "/home/bioinfo/Private/mrq/bin/Anaconda3/envs/cnvpytor/lib/python3.7/site-packages/cnvpytor/utils.py", line 762, in int1
    return int(int(x) == 1)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

```

I got vcf file through gatk 4.0.
What should I do? Thanks for reply.
CNVpytor Version 1.1

**Comment by m-rq** [comment]
The problem was solved and I unzipped the .gz file. Maybe CNVpytor does not support .gz files generated by GATK.

**Comment by Neato-Nick** [comment]
I ran into this problem, the Issue should stay open.

There are different errors for using gzipped and bgzipped VCFs. HTSlib doesn't read gzipped files, fortunately GATK uses bgzip. But if I have the tabix index file in the folder, I get this error. If I delete the tabix, cnvpytor can read the gzipped vcf and I just get a warning that the vcf file is not indexed.

**Comment by suvakov** [comment]
Yes, bgzip is readable only because we are using HTSlib. Is it exactly the same error:
```
  File ..., line 779, in gt_from_list
    haps = list(map(int1, l))
  File ..., line 762, in int1
    return int(int(x) == 1)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
as before?

**Comment by Neato-Nick** [comment]
Yep, same error. Also, I did install using the clone + local pip install method.

My VCF works decompressed or bg-zipped without a corresponding .tbi file. Even if I freshly generate the .tbi instead of relying on the one generated at the end of a GATK run.
Here's the full stack:
```
Traceback (most recent call last):
  File "/home/nicholas.carleson@usda-ars.orst.edu/.local/bin/cnvpytor", line 8, in <module>
    sys.exit(main())
  File "/home/nicholas.carleson@usda-ars.orst.edu/.local/lib/python3.8/site-packages/cnvpytor/__main__.py", line 284, in main
    app.vcf(args.vcf, chroms=args.chrom, sample=args.vcf_sample, no_counts=args.no_snp_counts,
  File "/home/nicholas.carleson@usda-ars.orst.edu/.local/lib/python3.8/site-packages/cnvpytor/root.py", line 347, in vcf
    self._read_vcf(vcf_file, chroms, sample, no_counts=no_counts, ad_tag=ad_tag, gt_tag=gt_tag, filter=filter,
  File "/home/nicholas.carleson@usda-ars.orst.edu/.local/lib/python3.8/site-packages/cnvpytor/root.py", line 272, in _read_vcf
    pos, ref, alt, nref, nalt, gt, flag, qual = vcff.read_chromosome_snp(c, sample, ad_tag=ad_tag,
  File "/home/nicholas.carleson@usda-ars.orst.edu/.local/lib/python3.8/site-packages/cnvpytor/vcf.py", line 162, in read_chromosome_snp
    gt.append(gt_from_list(rec.samples[sample][gt_tag], rec.samples[sample].phased))
  File "/home/nicholas.carleson@usda-ars.orst.edu/.local/lib/python3.8/site-packages/cnvpytor/utils.py", line 981, in gt_from_list
    haps = list(map(int1, l))
  File "/home/nicholas.carleson@usda-ars.orst.edu/.local/lib/python3.8/site-packages/cnvpytor/utils.py", line 964, in int1
    return int(int(x) == 1)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

```

**Comment by gevro** [comment]
Hi, I'm getting the same error. Has this been fixed?
