### ISSUE TITLE
IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by mdozmorov** [abyzovlab/CNVpytor#63]
Genotyping either of the two pythor files terminates on one region, `chr1:90030001-103790000`. 
```
/home/user/.local/lib/python3.9/site-packages/CNVpytor-1.1-py3.9.egg/cnvpytor/viewer.py:3782: RuntimeWarning: invalid value encountered in true_divide
Traceback (most recent call last):
  File "/home/user/.local/bin/cnvpytor", line 33, in <module>
    sys.exit(load_entry_point('CNVpytor==1.1', 'console_scripts', 'cnvpytor')())
  File "/home/user/.local/lib/python3.9/site-packages/CNVpytor-1.1-py3.9.egg/cnvpytor/__main__.py", line 225, in main
  File "/home/user/.local/lib/python3.9/site-packages/CNVpytor-1.1-py3.9.egg/cnvpytor/viewer.py", line 3815, in genotype_prompt
  File "/home/user/.local/lib/python3.9/site-packages/CNVpytor-1.1-py3.9.egg/cnvpytor/viewer.py", line 3783, in genotype_all
  File "/home/user/.local/lib/python3.9/site-packages/CNVpytor-1.1-py3.9.egg/cnvpytor/utils.py", line 557, in likelihood_baf_pval
IndexError: index 0 is out of bounds for axis 0 with size 0
```
The plot of this region looks typical
![test](https://user-images.githubusercontent.com/864945/132145437-15da834b-3c47-4829-87f5-e6a3df86f781.png)

And, the output of `cnvpytor -root sample1.pytor -ls` looks OK:
```
File created: 2021-09-03 21:31 using CNVpytor ver 1.1

Chromosomes with RD signal: chr1, chr2, chr3, chr4, chr5, chr6, chr7, chr8, chr9, chr10, chr11, chr12, chr13, chr14, chr15, chr16, chr17, chr18, chr19, chr20, chr21, chr22, chrX

Chromosomes with SNP signal: chr1, chr2, chr3, chr4, chr5, chr6, chr7, chr8, chr9, chr10, chr11, chr12, chr13, chr14, chr15, chr16, chr17, chr18, chr19, chr20, chr21, chr22, chrX, chrY

Using reference genome: hg19 [ GC: yes, mask: yes ]

Chromosomes with RD histograms [bin sizes]: chr10, chr11, chr12, chr13, chr14, chr15, chr16, chr17, chr18, chr19, chr1, chr20, chr21, chr22, chr2, chr3, chr4, chr5, chr6, chr7, chr8, chr9, chrX [10000, 100000]

Chromosomes with SNP histograms [bin sizes]: chr10, chr11, chr12, chr13, chr14, chr15, chr16, chr17, chr18, chr19, chr1, chr20, chr21, chr22, chr2, chr3, chr4, chr5, chr6, chr7, chr8, chr9, chrX, chrY [10000, 100000]

Chromosome lengths: {'chr1': '249250621', 'chr2': '243199373', 'chr3': '198022430', 'chr4': '191154276', 'chr5': '180915260', 'chr6': '171115067', 'chr7': '159138663', 'chr8': '146364022', 'chr9': '141213431', 'chr10': '135534747', 'chr11': '135006516', 'chr12': '133851895', 'chr13': '115169878', 'chr14': '107349540', 'chr15': '102531392', 'chr16': '90354753', 'chr17': '81195210', 'chr18': '78077248', 'chr19': '59128983', 'chr20': '63025520', 'chr21': '48129895', 'chr22': '51304566', 'chrX': '155270560', 'chrY': '59373566'}
```
What may be wrong?
Thanks,
Mikhail

**Comment by suvakov** [comment]
Not sure. Is it working for other regions? What was the bin size used for genotyping?

**Comment by mdozmorov** [comment]
Thank you, Milovan, yes, it works through ~10-15 regions and consistently breaks on that one. The bin size was 10000. It works with 100000, but naturally, the regions will be different. Seems like an edge case, which likely will occur under other circumstances. I ran out of ideas how to debug.

**Comment by suvakov** [comment]
I figured out what produce this error but not sure what is the best way to resolve it. There are two regions with different BAF (large CN3 and small CN5 - around 95Mbp). Because they are supported with a lot of SNPs, likelihood functions for both regions are narrow. Numerically they are not overlapping at all due to double precision. The result is a zero likelihood function that leads to division by zero. I can avoid this error in code and raise a warning but maybe there is a better way to address such situations. Let me discuss this with colleagues. Interesting issue. Thank you for finding it. Please let me know if you have any advice.

**Comment by m-rq** [comment]
I have similar output. I run :
`awk '{ print $2 } END { print "exit" }' ../3_calls/155_calls.300.tsv | cnvpytor -conf 1_ref_genome_conf_auto.py -root ../2_results/155.pytor -genotype 300`

The output was interrupted in a duplication area. 
```
/home/bioinfo/Private/mrq/bin/Anaconda3/envs/cnvpytor/lib/python3.7/site-packages/cnvpytor/viewer.py:3782: RuntimeWarning: invalid value encountered in true_divide
  lh /= np.sum(lh)
Traceback (most recent call last):
  File "/home/bioinfo/Private/mrq/bin/Anaconda3/envs/cnvpytor/bin/cnvpytor", line 8, in <module>
    sys.exit(main())
  File "/home/bioinfo/Private/mrq/bin/Anaconda3/envs/cnvpytor/lib/python3.7/site-packages/cnvpytor/__main__.py", line 225, in main
    view.genotype_prompt(list(map(binsize_type, args.genotype)), all=args.all)
  File "/home/bioinfo/Private/mrq/bin/Anaconda3/envs/cnvpytor/lib/python3.7/site-packages/cnvpytor/viewer.py", line 3815, in genotype_prompt
    self.genotype_all(bin_sizes, [line], interactive=True)
  File "/home/bioinfo/Private/mrq/bin/Anaconda3/envs/cnvpytor/lib/python3.7/site-packages/cnvpytor/viewer.py", line 3783, in genotype_all
    baf, baf_p = likelihood_baf_pval(lh)
  File "/home/bioinfo/Private/mrq/bin/Anaconda3/envs/cnvpytor/lib/python3.7/site-packages/cnvpytor/utils.py", line 557, in likelihood_baf_pval
    ix = np.where(likelihood == max_lh)[0][0]
IndexError: index 0 is out of bounds for axis 0 with size 0

```

**Comment by suvakov** [comment]
It should be working now. We used logarithm of likelihood to avoid divergence.

**Comment by mdozmorov** [comment]
Thanks, Milovan, it helped. I encountered another error while genotyping, please, let me know if I should open a separate issue.

While genotyping chrX, CNVpytor breaks after `chrX:153780001-154600000` on hg19. The chrX size is 156,040,895, so things may be unpredictable at the end of a chromosome. Still, this error prevents automation. Can you look into it?
```
chrX:149080001-149200000	2.0826	3.800631e+03	2.649367e+09	0.0940	0.0172	0	1.0000	23	0	0.4950	5.025126e-01
chrX:149380001-152230000	1.9590	7.763168e-01	2.849193e+09	0.0333	0.0000	47300	1.0000	1045	4	0.1500	4.929284e-02
chrX:153780001-154600000	2.0130	1.038809e+03	2.796739e+09	0.1243	0.0000	660800	1.0000	80	6	0.3550	3.237325e-10
/Users/mdozmorov/miniconda3/envs/cnvpytor/lib/python3.9/site-packages/cnvpytor/utils.py:360: RuntimeWarning: Mean of empty slice
  aver = np.nanmean(rd[start:end])
/Users/mdozmorov/.local/lib/python3.9/site-packages/numpy-1.21.2-py3.9-macosx-10.9-x86_64.egg/numpy/lib/nanfunctions.py:1670: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/Users/mdozmorov/miniconda3/envs/cnvpytor/lib/python3.9/site-packages/cnvpytor/utils.py:368: RuntimeWarning: Mean of empty slice
  aver = np.nanmean(rd[start:end])
Traceback (most recent call last):
  File "/Users/mdozmorov/miniconda3/envs/cnvpytor/bin/cnvpytor", line 8, in <module>
    sys.exit(main())
  File "/Users/mdozmorov/miniconda3/envs/cnvpytor/lib/python3.9/site-packages/cnvpytor/__main__.py", line 225, in main
    view.genotype_prompt(list(map(binsize_type, args.genotype)), all=args.all)
  File "/Users/mdozmorov/miniconda3/envs/cnvpytor/lib/python3.9/site-packages/cnvpytor/viewer.py", line 3821, in genotype_prompt
    self.genotype_all(bin_sizes, [line], interactive=True)
  File "/Users/mdozmorov/miniconda3/envs/cnvpytor/lib/python3.9/site-packages/cnvpytor/viewer.py", line 3754, in genotype_all
    e2 = gaussianEValue(stat[4], stat[5], his_p, bin1, bin2 + 1) * 2.9e9
  File "/Users/mdozmorov/miniconda3/envs/cnvpytor/lib/python3.9/site-packages/cnvpytor/utils.py", line 369, in gaussianEValue
    max = np.nanmax(rd[start:end])
  File "<__array_function__ internals>", line 5, in nanmax
  File "/Users/mdozmorov/.local/lib/python3.9/site-packages/numpy-1.21.2-py3.9-macosx-10.9-x86_64.egg/numpy/lib/nanfunctions.py", line 441, in nanmax
    res = np.amax(a, axis=axis, out=out, **kwargs)
  File "<__array_function__ internals>", line 5, in amax
  File "/Users/mdozmorov/.local/lib/python3.9/site-packages/numpy-1.21.2-py3.9-macosx-10.9-x86_64.egg/numpy/core/fromnumeric.py", line 2754, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/Users/mdozmorov/.local/lib/python3.9/site-packages/numpy-1.21.2-py3.9-macosx-10.9-x86_64.egg/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity
```

**Comment by suvakov** [comment]
Hi @mdozmorov, sorry for delay. Can you share pytor file with me? If so, please send me on email (suvakov at gmail). Thanks, Milovan
