### ISSUE TITLE
1. The function of "Annotating in joint_calls" can be used in custom reference Genome? 2. There is a problem with the output of compare plot.

### ISSUE THREAD

**Issue by m-rq** [abyzovlab/CNVpytor#66]
Question 1:
I used the yeast reference genome, not the human genome in CNVpytor.
I followed the tutorial "merging.md". If I type "set annotate", then type "print joint_calls" the output is:

```
Traceback (most recent call last):
  File "/home/bioinfo/Private/mrq/bin/Anaconda3/envs/cnvpytor/bin/cnvpytor", line 8, in <module>
    sys.exit(main())
  File "/home/bioinfo/Private/mrq/bin/Anaconda3/envs/cnvpytor/lib/python3.7/site-packages/cnvpytor/__main__.py", line 271, in main
    view.prompt()
  File "/home/bioinfo/Private/mrq/bin/Anaconda3/envs/cnvpytor/lib/python3.7/site-packages/cnvpytor/viewer.py", line 503, in prompt
    self.print_simple_joint_calls()
  File "/home/bioinfo/Private/mrq/bin/Anaconda3/envs/cnvpytor/lib/python3.7/site-packages/cnvpytor/viewer.py", line 1229, in print_simple_joint_calls
    annotator = Annotator(self.reference_genome)
  File "/home/bioinfo/Private/mrq/bin/Anaconda3/envs/cnvpytor/lib/python3.7/site-packages/cnvpytor/annotator.py", line 28, in __init__
    self.url_template = reference_genome["ensembl_api_region"]
KeyError: 'ensembl_api_region'
```

The function of "Annotating in joint_calls" can be used in custom reference Genome?

Question 2:
I want to output compare plot. I followed the tutorial "compare.md". The file (*.png) was created, but there is nothing in the image (I omit "set rd_use_mask", because I do not have mask file).

```
cnvpytor -conf 1_ref_genome_conf_auto.py -root 2_root.pytor 2_root_upback.pytor -view 500
set style classic
compare NC_001133.9:1-10k NC_001133.9:11k-20k
```

```
2_root.pytor	NC_001133.9:1-10k	NC_001133.9:11k-20k	359.0108	41.4968	286.9653	162.9490	4.686765e-02	1.2511	0.2064
2_root_upback.pytor	NC_001133.9:1-10k	NC_001133.9:11k-20k	359.0108	41.4968	286.9653	162.9490	4.686765e-02	1.2511	0.2064
```

`save compare.png`

**Comment by suvakov** [comment]
A 1)
CNVpytor is using Ensembl API for annotation. If reference genome you are using is supported by Ensembl you should specify API url if reference genome config, e.g. for hg19 human it is:
```
"hg19": {
            "name": "GRCh37",
            "species": "human",
            "chromosomes": OrderedDict(...),
            "gc_file": ...,
            "mask_file": ...,
            "ensembl_api_region": "https://grch37.rest.ensembl.org/overlap/region/human/{region}?content-type=application/json;feature=gene;"
        },
```

Here ```{region}``` is replaced by region during annotation.

A 2)
Sorry, example was outdated. You should type ```set plot``` before ```compare ...``` command. 

(alternative) If you want to avoid plotting on screen use:
```
cnvpytor> set style classic
cnvpytor> set plot
cnvpytor> set output_filename output.png
cnvpytor> compare NC_001133.9:1-10k NC_001133.9:11k-20k
```

Thank you!

**Comment by m-rq** [comment]
Thanks a lot. It works. Perfectly!!!
